### ISSUE TITLE
 node-nats has new update for token authn

### ISSUE THREAD

**Issue by gaozhidf** [joshglendenning/websocket-nats#1]
hi,

i user websocket-nats, and it work well except for token auth

node-nats has new update for token auth, and can you update your nats.js 

FYI:
[node-nats update for token auth](https://github.com/nats-io/node-nats/issues/96)

**Comment by isobit** [comment]
Oh hey, cool, I didn't know they added that feature, I could use that as well. I'll update that ASAP.

**Comment by gaozhidf** [comment]
yeah, token auth is useful part, but it seems other clients like jnats lacks it T_T
