### ISSUE TITLE
websocket connect with hostname and pathname

### ISSUE THREAD

**Issue by gaozhidf** [joshglendenning/websocket-nats#3]
hi,

it's glad to see it updated :+1:  . 

And now i met a new problem -  i use a proxy server before my websocket server, but url `ws://127.0.0.1/websocket`, always be changed as `ws://127.0.0.1:null`

```
exports.createConnection = function(url) {
	// The url is rebuilt to avoid including the auth credentials.
	var portSuffix = (url.port)? ':' + url.port : '';
	return new WebSocketProxy(url.protocol + '//' + url.hostname + portSuffix);
}
```

can you update it for supporting `url.hostname+url.pathname`, but no port.

**Comment by isobit** [comment]
Oops! I'll update it when I get home later.
