### ISSUE TITLE
websocket-nats can't publish binary message(Uint8Array)

### ISSUE THREAD

**Issue by dbskccc** [joshglendenning/websocket-nats#4]
we want to publish protobuf.js encoded message,when publish the encoded Uint8Array message,the encoded frame is not correct.

`nats_con=NATS.connect("ws://192.168.1.103:4223");
nats_con.publish("foo","hello string from websocket");
nats_con.subscribe("foo",function (msg) {
    console.log("msg:",msg)
});
//the frame of the below publish is error
nats_con.publish("foo",new Uint8Array(16) );
console.log("script has exec finished");`

**Comment by dbskccc** [comment]
well,translate the buffer to string first,it works.

message_str=String.fromCharCode.apply(null, buf);
nats_con.publish("foo",message_str )

**Comment by isobit** [comment]
Glad you were able to find a workaround!

This functionality is actually supported in node-nats using the `Buffer` API, which is shimmed by [this](https://github.com/feross/buffer) in the browser. If you're using webpack or browserify, you should be able to use `Buffer` as it works in node.

However, I think it's a good idea to support `TypedArray`/`ArrayBuffer` as an equivalent to `Buffer` for binary messages out of the box, so I'm reopening this issue.

**Comment by isobit** [comment]
It was a simple fix actually, you should be able to pass a `Uint8Array` directly to `publish` now.

**Comment by dbskccc** [comment]
thanks
