### ISSUE TITLE
output a unuglify and not minimize js file for dev

### ISSUE THREAD

**Issue by dbskccc** [joshglendenning/websocket-nats#5]
now the dist only output an uglify and minimize bundle.js.
it should be one unuglify and not minimize for dev, i suggest file name
websocket-nats.js and rename bundle.js to websocket-nats-min.js

**Comment by isobit** [comment]
I've added the normal, dev, and minified versions and updated the README with how to use them via the RawGit CDN.

**Comment by dbskccc** [comment]
good job! thanks for your work.
