### ISSUE TITLE
Using setImmediate

### ISSUE THREAD

**Issue by pward123** [joshglendenning/websocket-nats#7]
Is there some webpack magic going on here with regards to setImmediate?  Given the canIuser for setImmediate, `setTimeout(()=>{}, 0)` seems like a better call

**Comment by isobit** [comment]
Webpack ends up shimming `setImmediate`, if that's what you're wondering. I traced the shim though [node-libs-browser](https://github.com/webpack/node-libs-browser) to the [`setImmediate`](https://www.npmjs.com/package/setimmediate) package, if you're interested in the implementation.

The use of  `setImmediate` was inherited from [`node-nats`](https://github.com/nats-io/node-nats), so I defer to that for explanation. Perhaps a `setTimeout(..., 0)` would be better, but I prefer to keep `nats.js` as close to the `node-nats` implementation as possible and just shim the node APIs.

**Comment by pward123** [comment]
Thanks for the quick response. I was attempting to make the library work in a Meteor client. 

Since Meteor doesn't shim setImmediate nor support the object form of the "browser" property in package.json, I ended up forking the project and patching both issues.

**Comment by isobit** [comment]
I hadn't considered browser consumption of the library without using webpack, certainly it would be more convenient to not depend on webpack's shims for use cases like yours. It may make sense to merge those patches back here, although my initial impression is that there may be a way to shim without webpack, that way the library can be used in a nodejs environment.
